# WSL
alias exp='explorer.exe .'
alias notepad='notepad.exe'
alias ..='cd ../'
alias ...='cd ../../'
alias c='cd /mnt/c/'
alias d='cd /mnt/d/'
alias desk='cd /mnt/c/Users/subra/Desktop/'
alias docs='cd /mnt/c/Users/subra/Documents/'
alias win-proj='cd /mnt/d/Projects'
alias lin-proj='cd /home/subrat/projects'
alias unsw-ssh='ssh -Y z5266273@login.cse.unsw.edu.au'
alias bashrc='code /home/subrat/.bash_aliases'
alias get-ssh='cat ~/.ssh/id_rsa.pub | xclip -sel clip'

# Linux
alias exp='nautilus . &'
alias note='gedit'
alias ..='cd ../'
alias ...='cd ../../'
alias d='cd /run/media/subrat/DATA'
alias unsw-ssh='ssh -Y z5266273@login.cse.unsw.edu.au'
alias bashrc='code /home/subrat/.bash_aliases'
alias get-ssh='cat ~/.ssh/id_rsa.pub | xclip -sel clip'
